### ISSUE TITLE
Episode Suggestion: The "Materialized View" Pattern

### ISSUE THREAD

**Issue by chrisreddington** [chrisreddington/cloudwithchris.com#81]
Cover this Cloud Design Pattern as part of the "Architecting for the Cloud, one deployment pattern at a time" series.

Suggestion submitted through the form at https://forms.office.com/Pages/ResponsePage.aspx?id=I8_hAe_rSkSatzbwI0Rs1nhBo3a5mW9AuJOwL1Kt0n9UQVcyOFZFNkdXU0FGNTM0Uk0zUEdPT1VFNy4u

**Comment by chrisreddington** [comment]
I think that we could introduce both this and #71 in the same session (both distinctly separate at the beginning), and then talking about how these patterns can be used together/with some kind of tangible examples by the end of the session.

Would December work for you @StephJMartin? I'm making some tweaks to my speaker booking form, so will send that out so we can get a slot booked ASAP when I've made the tweaks :)

**Comment by StephJMartin** [comment]
Chris yes December works for me as long as it's before the 17th
