### ISSUE TITLE
Episode Suggestion: The "Valet Key" Pattern

### ISSUE THREAD

**Issue by chrisreddington** [chrisreddington/cloudwithchris.com#94]
Cover this Cloud Design Pattern as part of the "Architecting for the Cloud, one deployment pattern at a time" series.

Suggestion submitted through the form at https://forms.office.com/Pages/ResponsePage.aspx?id=I8_hAe_rSkSatzbwI0Rs1nhBo3a5mW9AuJOwL1Kt0n9UQVcyOFZFNkdXU0FGNTM0Uk0zUEdPT1VFNy4u

**Comment by vermegi** [comment]
Hi Chris, this is a comment just for you :)

**Comment by algorni** [comment]
ciao

**Comment by ralarcon** [comment]
Waiting to see it!

**Comment by petpipe-msft** [comment]
@chrisreddington I can do this in March or something like if no one is picking it up

**Comment by petpipe-msft** [comment]
Looks like I can do this when we sync up in a few days... @chrisreddington
